In [4]:
!pip install opencv-python

In [2]:
import numpy as np
import cv2

In [23]:
#이미지파일 불러오기
write = cv2.imread('./test1.jpg', cv2.IMREAD_COLOR)
#이미지파일을 그레이스케일로
write_gray = cv2.cvtColor(write, cv2.COLOR_BGR2GRAY)
#이미지를 이진수로 변환한듯?
ret, thresh = cv2.threshold(write_gray, 150, 255, cv2.THRESH_BINARY_INV)

#출력해서 무슨값인지 알기
print(write_gray)
print(ret)
print(thresh)

#thresh 이미지는 영역반전 이미지였음. 마스크 같이
cv2.imshow('resultat', thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
150.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
# dilate the write
elem = cv2.getStructuringElement(cv2.MORPH_RECT, (4, 4), (2, 2))
dilat = cv2.dilate(thresh, elem, iterations=1) #이것도 마스크처럼 생겼는데
contours, hierarchy = cv2.findContours(dilat, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

print(dilat)
print(contours)
print(hierarchy)
#이미지에서 무슨 정보인가봄 찾아봐야겠다.

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(array([[[301, 616]],

       [[300, 617]],

       [[299, 617]],

       ...,

       [[311, 617]],

       [[309, 617]],

       [[308, 616]]], dtype=int32), array([[[677, 342]],

       [[676, 343]],

       [[674, 343]],

       ...,

       [[693, 343]],

       [[691, 343]],

       [[690, 342]]], dtype=int32), array([[[291, 177]],

       [[290, 178]],

       [[289, 178]],

       ...,

       [[305, 191]],

       [[305, 181]],

       [[301, 177]]], dtype=int32))
[[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [-1  1 -1 -1]]]


In [26]:
for cnt in contours:
    if cv2.contourArea(cnt) > 1600: # only keep the writing text
        box = cv2.minAreaRect(cnt)
        (pos, size, angle) = box
        box = cv2.boxPoints(box)
        box = np.int0(box)
        cv2.drawContours(write, [box], 0, (0,255,0), 2)
        angle = angle if size[0] > size[1] else angle + 90
        pos = (cnt[cnt[:, :, 0].argmin()][0][0], cnt[cnt[:, :, 1].argmin()][0][1])
        print(angle)
        if -2 <= angle <= 2:
            cv2.putText(write, 'Level', pos, cv2.FONT_HERSHEY_SIMPLEX, 0.7, (190, 123, 68), 2)
        elif angle < -2:
            cv2.putText(write, 'Ascending', pos, cv2.FONT_HERSHEY_SIMPLEX, 0.7, (190, 123, 68), 2)
        elif 2 < angle:
            cv2.putText(write, 'Descending', pos, cv2.FONT_HERSHEY_SIMPLEX, 0.7, (190, 123, 68), 2)

cv2.imshow('resultat', write)

#계속 응답없음 일때 해결법
cv2.waitKey(0)
cv2.destroyAllWindows()

4.13608980178833
78.06439971923828
1.9687672853469849


In [26]:
write = cv2.imread('./line_eng2.jpg', cv2.IMREAD_COLOR)
write_gray = cv2.cvtColor(write, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(write_gray, 150, 255, cv2.THRESH_BINARY_INV)

# dilate the write
elem = cv2.getStructuringElement(cv2.MORPH_RECT, (4, 4), (2, 2))
dilat = cv2.dilate(thresh, elem, iterations=1)
contours, hierarchy = cv2.findContours(dilat, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    if cv2.contourArea(cnt) > 1600: # only keep the writing text
        box = cv2.minAreaRect(cnt)
        (pos, size, angle) = box
        box = cv2.boxPoints(box)
        box = np.int0(box)
        cv2.drawContours(write, [box], 0, (0,255,0), 2)
        angle = angle if size[0] > size[1] else angle - 90
        pos = (cnt[cnt[:, :, 0].argmin()][0][0], cnt[cnt[:, :, 1].argmin()][0][1])
        print(angle)
        if -2 <= angle <= 2:
            cv2.putText(write, 'Level', pos, cv2.FONT_HERSHEY_SIMPLEX, 0.7, (190, 123, 68), 2)
        elif angle < -2:
            cv2.putText(write, 'Ascending', pos, cv2.FONT_HERSHEY_SIMPLEX, 0.7, (190, 123, 68), 2)
        elif 2 < angle:
            cv2.putText(write, 'Descending', pos, cv2.FONT_HERSHEY_SIMPLEX, 0.7, (190, 123, 68), 2)

cv2.imshow('resultat', write)

#계속 응답없음 일때 해결법
cv2.waitKey(0)
cv2.destroyAllWindows()

0.0
-1.1232986450195312
90.0
90.0
1.4912837743759155
86.18592071533203
8.56914234161377
7.628149032592773
-82.52844095230103
66.80140686035156
-9.398239135742188
